export const courses = [
  {
    id: 1,
    courseName: 'React: Getting Started',
    isPopular: true,
    isNew: false,
    authorName: 'Samuel Eto',
    publishedDate: '2020-06-12',
    level: 'Beginner',
    numOfRates: 3.5,
    score: 3587,
    courseLength: '9h2m',
  },
  {
    id: 2,
    courseName: 'Javascript: Getting Started',
    isPopular: false,
    isNew: false,
    authorName: 'Romeo Lukaku',
    publishedDate: '2021-01-11',
    level: 'Beginner',
    numOfRates: 4.5,
    score: 196,
    courseLength: '4h2m',
  },
  {
    id: 3,
    courseName: 'I dont know JS',
    isPopular: true,
    isNew: true,
    authorName: 'Giccwo EtKansaoo',
    publishedDate: '2020-04-25',
    level: 'Beginner',
    numOfRates: 5.0,
    score: 2101,
    courseLength: '11h10m',
  },
  {
    id: 4,
    courseName: 'Design pattern, Javascript',
    isPopular: false,
    isNew: false,
    authorName: 'Tom Ford',
    publishedDate: '2019-09-14',
    level: 'Middle',
    numOfRates: 4.5,
    score: 1102,
    courseLength: '12h2m',
  },
  {
    id: 5,
    courseName: 'My SQL, Relationship Database RSMDC',
    isPopular: true,
    isNew: true,
    authorName: 'Makr Kizamic',
    publishedDate: '2020-04-25',
    level: 'Advance',
    numOfRates: 4.5,
    score: 2992,
    courseLength: '8h20m',
  },
  {
    id: 6,
    courseName: 'VueJS: Create component scalable',
    isPopular: true,
    isNew: false,
    authorName: 'Evan You',
    publishedDate: '2021-01-02',
    level: 'Beginner',
    numOfRates: 3.5,
    score: 6221,
    courseLength: '14h5m',
  },
  {
    id: 7,
    courseName: 'C#: Getting Started',
    isPopular: false,
    isNew: false,
    authorName: 'Karim Benzema',
    publishedDate: '2011-01-11',
    level: 'Beginner',
    numOfRates: 3.5,
    score: 1906,
    courseLength: '14h2m',
  },
  {
    id: 8,
    courseName: 'Github best pratice',
    isPopular: true,
    isNew: true,
    authorName: 'Github team',
    publishedDate: '2021-02-25',
    level: 'Beginner',
    numOfRates: 3.0,
    score: 1001,
    courseLength: '1h10m',
  },
  {
    id: 9,
    courseName: 'You dont know JS',
    isPopular: false,
    isNew: false,
    authorName: 'Balenciaga',
    publishedDate: '2016-02-21',
    level: 'Middle',
    numOfRates: 5,
    score: 2995,
    courseLength: '30h2m',
  },
  {
    id: 10,
    courseName: 'SQL Server, Build scalable application',
    isPopular: true,
    isNew: true,
    authorName: 'Ronan Keuman',
    publishedDate: '2018-11-25',
    level: 'Middle',
    numOfRates: 4.5,
    score: 292,
    courseLength: '12h20m',
  },
]
